using System.IO;
using System.Text.RegularExpressions;
using SMME = Sucrose.Manager.Manage.Engine;
using SMMRC = Sucrose.Memory.Manage.Readonly.Content;
using SMMRF = Sucrose.Memory.Manage.Readonly.Folder;
using SMMRG = Sucrose.Memory.Manage.Readonly.General;
using SMMRP = Sucrose.Memory.Manage.Readonly.Path;
using SSEMI = Sucrose.Shared.Engine.Manage.Internal;
using SSEMPMI = Sucrose.Shared.Engine.MpvPlayer.Manage.Internal;
using SSSHF = Sucrose.Shared.Space.Helper.Filing;
using SSSHR = Sucrose.Shared.Space.Helper.Regexer;

namespace Sucrose.Shared.Engine.MpvPlayer.Helper
{
    internal static class Initialize
    {
        public static void Start()
        {
            SSEMPMI.MpvPath = Path.Combine(SMMRP.ApplicationData, SMMRG.AppName, SMMRF.Cache, SMMRF.MpvPlayer);

            if (!Directory.Exists(SSEMPMI.MpvPath))
            {
                Directory.CreateDirectory(SSEMPMI.MpvPath);
            }

            Config();
        }

        private static void Config()
        {
            SSEMPMI.MpvConfig = Path.Combine(SSEMPMI.MpvPath, SMMRC.MpvPlayerConfig);

            string Content = string.Join(Environment.NewLine, SSEMI.MpvConfig);

            if (File.Exists(SSEMPMI.MpvConfig))
            {
                Content = SSSHF.Read(SSEMPMI.MpvConfig);
            }

            if (SSSHR.IsMatch(Content, @"^hwdec=", RegexOptions.Multiline))
            {
                if (SMME.HardwareAcceleration)
                {
                    Content = SSSHR.Replace(Content, @"^hwdec=.*$", "hwdec=auto-safe", RegexOptions.Multiline);
                }
                else
                {
                    Content = SSSHR.Replace(Content, @"^hwdec=.*$", "hwdec=no", RegexOptions.Multiline);
                }
            }
            else
            {
                Content += Environment.NewLine + Environment.NewLine + "# Auto Generated by Sucrose #";

                if (SMME.HardwareAcceleration)
                {
                    Content += Environment.NewLine + "hwdec=auto-safe";
                }
                else
                {
                    Content += Environment.NewLine + "hwdec=no";
                }

                Content += Environment.NewLine + "# Auto Generated by Sucrose #";
            }

            SSSHF.Write(SSEMPMI.MpvConfig, Content);
        }
    }
}